### ISSUE TITLE
Missing documentation for what cluster `--protected` means

### ISSUE THREAD

**Issue by mbforbes** [beaker/docs#30]
```bash
$ beaker cluster create --help
Create a new cluster

Usage:
  beaker cluster create <name> [flags]

Flags:
      --cpus float        Minimum CPU cores per node, e.g. 7.5
      --gpu-type string   Type of GPU: k80, p100, v100, or t4
      --gpus int          Number of GPUs per node: 1, 2, 4, or 8
  -h, --help              help for create
      --max-size int      Maximum number of nodes
      --memory string     Minimum memory per node, e.g. 6.5GiB
      --preemptible       Enable cheaper but more volatile nodes
      --protected         Mark cluster as protected

Global Flags:
      --format string   Output format
  -q, --quiet           Quiet mode
```

![image](https://user-images.githubusercontent.com/1170062/125530725-34b178d2-7c09-4811-bc2b-4f4bb326e787.png)

![image](https://user-images.githubusercontent.com/1170062/125530947-d2486572-164b-4177-8e30-a03fa2fc6658.png)

**Comment by codeviking** [comment]
I found [this comment](https://github.com/allenai/beaker-service/blob/4d0772e8cbf84c2ab073e2def45522d15c9a2625/api/cluster.go#L84):

```
// Protected marks the cluster as a protected resource, ensuring only
// administrators can modify/delete it. Only administrators can create them.
```

So it's just a way to prevent against accidental deletion,.

I'm going to create a ticket to add documentation for this. Let me know if this doesn't answer your question!

**Comment by codeviking** [comment]
I cut [a ticket](https://github.com/allenai/beaker-service/issues/1569) for improving this documentation.
